OPD Mental health report
EGPAFMalawiHIS/BHT-EMR-API pull request #21
Opened 2024-06-18 07:02 UTC by brian-mw

Report should return array of patients and not count

2024-06-18 07:29 UTC, KytonThaundi approved these changes

2024-06-18 07:37 UTC, Skipper-116 approved these changes

2024-06-24 08:36 UTC, uniquedj95 requested changes
Revise age groups to match with report's specified age groups.

i.e. `0 - 15 years` and `>=16 years`

2024-06-25 09:25 UTC, uniquedj95 approved these changes

2024-06-26 10:21 UTC, merged