Adding ART Start Date to Drilldowns
EGPAFMalawiHIS/BHT-EMR-API pull request #33
Opened 2024-07-02 09:41 UTC by Skipper-116

## Context
* We have a request to add art start dates to the drilldowns
* This PR adds the expected key to the different endpoints the frontend hits when drilling down on clients in reports.

## Ticket
[Shortcut Ticket](https://app.shortcut.com/egpaf-2/story/3781/the-drill-down-on-all-reports-should-have-an-art-start-date)
[Github Andrew PR](https://github.com/EGPAFMalawiHIS/HIS-Core/pull/1028)

2024-07-02 11:23 UTC, KytonThaundi approved these changes

2024-07-02 11:24 UTC, KytonThaundi approved these changes

2024-07-02 11:54 UTC, andie23 requested changes
The following endpoint is not presenting ART start date:

http://localhost:3000/api/v1/clients?person_ids=223,659&=

```json
{
	"0": {
		"person_id": 659,
		"gender": "F",
		"birthdate": "1997-03-03",
		"birthdate_estimated": 0,
		"dead": 0,
		"death_date": null,
		"cause_of_death": null,
		"creator": 1,
		"date_created": "2024-02-27T13:08:10.000+02:00",
		"changed_by": 1,
		"date_changed": "2024-03-14T09:30:11.000+02:00",
		"voided": 0,
		"voided_by": null,
		"date_voided": null,
		"void_reason": null,
		"uuid": "2715126d-c1ca-4b3d-9c3b-6f0b5800c074",
		"identifier": "MOH-ARV-2"
	}
}
```
# Disaggregated report errors
When i open disaggregated reports, i'm getting the following error:
`errors	[ "undefined method `casecmp?' for false:FalseClass" ]`

payload:

2024-07-02 12:35 UTC, Skipper-116 commented
First issue resolved. Second issue we will need more details we are failing to recreate it

2024-07-03 07:00 UTC, andie23 approved these changes

2024-07-04 10:52 UTC, merged